### ISSUE TITLE
Ограниченные лимиты платежей

### ISSUE THREAD

**Issue by Tarlord** [TinkoffCreditSystems/business-openapi#19]
Добрый день,
на https://business.tinkoff.ru/openapi/docs#operation/PaymentsCorePay
описаны лимиты платежей:
максимальная сумма одного платежа - 100000 рублей
максимальная сумма платежей в день - 100000 рублей
максимальная сумма платежей в месяц - 1000000 рублей
максимальное количество платежей в день на одного контрагента - 3

Вопрос - это максимальные лимиты переводов возможные по апи или их возможно расширить имея аккаунт с более продвинутым тарифом?

**Comment by ttemnov** [comment]
Можете написать на openapi@tinkoff.ru и лимиты изменят :)
