### ISSUE TITLE
Сплит принятого платежа

### ISSUE THREAD

**Issue by Gertz1** [TinkoffCreditSystems/business-openapi#23]
Добрый день.
Предусмотрено ли в API разделение принятого платежа - часть зачисляется на свой счет, а часть уходит на счет партнера?

**Comment by ttemnov** [comment]
Привет, можете делать следующим образом: 

1. https://business.tinkoff.ru/openapi/docs#operation/getApiV1Bank-statement - получить выписку и увидеть новую операцию
2. Создать два платежа на базе поступления https://business.tinkoff.ru/openapi/docs#operation/PaymentsCorePay
