### ISSUE TITLE
Получение динамической ссылки для СБП

### ISSUE THREAD

**Issue by andreytr** [TinkoffCreditSystems/business-openapi#24]
Сейчас есть возможность получить статический QR-код для приема оплат по СБП от физ лиц (система быстрых платежей). 

Но требуется еще иметь возможность создавать такие коды под каждую покупку. Скажем в кафе при оплате столика или заказа через СБП с уже зашитой суммой и автоматическим webhook при оплате.

**Comment by GI7PM878** [comment]
+100000 Динамический QR очень нужен. Вводные можно по API передавать в Тинькоф

**Comment by gormih** [comment]
+100500
Всеми руками голосуем!

**Comment by leonid-shamanaev** [comment]
Добрый день! Такая возможность уже есть.

https://acdn.tinkoff.ru/static/documents/merchant_api_protocoI_eacq.pdf

По ссылке можно найти API Интернет-эквайринга, в котором описаны методы получения динамического QR-кода.
Информацию об успешной оплате можно получать либо через метод GetState, либо через Callback по URL, который вы укажете в личном кабинете.

Схема работы по QR отражена на 43 странице.

**Comment by gormih** [comment]
> Схема работы по QR отражена на 43 странице.

На 44ой.
