### ISSUE TITLE
Коды валют

### ISSUE THREAD

**Issue by devdmkr** [TinkoffCreditSystems/business-openapi#3]
Где можно посмотреть коды валют счетов?

**Comment by GSatosov** [comment]
Добрый день,

Коды валют в апи из ОКВ, цифрами (для рублей, к примеру, — 643). Мы дополним документацию, чтобы это было более понятно.

**Comment by GSatosov** [comment]
Добрый день,

Улучшение документации зарелизили. Закрываю issue.
