### ISSUE TITLE
Возможность выпускать токены с разными привилегиями

### ISSUE THREAD

**Issue by AndreiOrlovGH** [TinkoffCreditSystems/business-openapi#4]
Хорошо бы реализовать возможность выпускать несколько токенов с разными привилегиями, например:
Токен1 - readonly для раздела оплат, доступ в остальные разделы запрещён, разрешённые IP: ****;
Токен2 - Возможность проведения оплаты по уже выставленным счетам, readonly для остальных разделов, разрешённые IP: *****

ну и т.п. Т.е. примерно как в Github при создании токена: можно включить/выключить любую опцию. Так будет безопаснее, если токен нужен не "для всего", а для чего-то специализированного.

**Comment by GSatosov** [comment]
Добрый день,

Данная функциональность есть в планах, но не на ближайшее время.

**Comment by ttemnov** [comment]
@StudyHelp 

Реализовали данную функциональность. 
Если настройка доступов вдруг неполна и не решает твоей задачи, то создай дополнительную issue, пожалуйста.

**Comment by ttemnov** [comment]
По работе именно с ограничениям IP будет отдельная задача, мы анализируем это.
