### ISSUE TITLE
Партнерский сценарий для получения операций по бизнес картам

### ISSUE THREAD

**Issue by GI7PM878** [TinkoffCreditSystems/business-openapi#6]
Добрый день, 

1. Пожалуйста поясните какие риски несанкционированных действий со средствами на счетах несет Партнерский сценарий OpenApi. Предполагается использовать его для получения операций по бизнес картам/счетам.
2. Как можно ограничить СелфСервис сценарий доступом к реестру операций и получению данных, и исключить формирование платежек, сотрудников, и безакцептных выплат?
3. СелфСервис сценарий можно считать безопасным если логины доступа к нашему операционному управляющему серверу не хранятся на носителях (он остается только "в голове" у оператора разработки)? 

Заранее большое спасибо за развернутый ответ!

**Comment by ttemnov** [comment]
1. Подключение идет по защищенному https каналу. Сама авторизация выполняется по безопасному протоколу oauth. При использовании openapi только для получение операций можно ограничить область действие токена, чтобы ничего другого по нему делать было нельзя. При использовании партнерского сценарии клиент Тинькофф Бизнес сам выбирает, какие действие со своим счетом разрешать партнеру. Подробнее об этом можно почитать в [нашей документации](https://business.tinkoff.ru/openapi/docs)

2. При получение токена вы можете настроить его разрешения 

3. Авторизация по сценарию [Селф-сервис](https://business.tinkoff.ru/openapi/docs#section/Scenarij-Self-Servis) происходит с помощью bearer токена. Этот токен ни в коем случае нельзя передавать третьим лицам, а хранить рекомендуется в недоступном для третьих лиц месте. В любом случае все имея только токен можно использовать только те методы,  некоторые у этого токена есть разрешение. Разрешения (scopes) можно настроить при генерации. Все методы openapi, которые несут финансовый риск, закрыты современным протоколом mTLS. Чтобы злоумышленник смог получить доступ к таким методам, он должен иметь не только токен, а так же [сертификат и приватный ключ](https://business.tinkoff.ru/openapi/docs#section/Sertifikaty). 

Если у вас остались вопросы, то откройте новый issue.
