### ISSUE TITLE
КПП юр лица при создании счета

### ISSUE THREAD

**Issue by andreytr** [TinkoffCreditSystems/business-openapi#8]
Доброго дня!

При создании счета не получается указать КПП юр лица, как это можно сделать?

**Comment by ttemnov** [comment]
Доброго дня! Взято в работу :)

**Comment by ttemnov** [comment]
Добрый день, реализовано в релизе Реализовоно https://business.tinkoff.ru/openapi/docs#section/Release-Notes/9-noyabrya-2020
