### ISSUE TITLE
Не отображаются некоторые данные счета в личном кабинете

### ISSUE THREAD

**Issue by andreytr** [TinkoffCreditSystems/business-openapi#9]
Доброго дня!

Если счет сгенерировать через API, то в личном кабинете не отображается email получателя счета и не фиксируются единицы в счете.

Это воспроизводится при создании акта на основе счета. Создаем акт на основе счета, созданного по API и нужно дополнять форму недостающими данными. Этой проблемы нет, если счет создан вручную в личном кабинете.

**Comment by ttemnov** [comment]
Поправлено в релизе https://business.tinkoff.ru/openapi/docs#section/Release-Notes/9-noyabrya-2020
